name: gmail_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  device_preview: ^1.2.0
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_lorem: ^2.0.0
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  responsive_builder: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
